### ISSUE TITLE
cant find keybind

### ISSUE THREAD

**Issue by aguyi** [theyareonit/Click-Between-Frames#10]
i might just be an idiot, but i cant find the keybind for this mod

**Comment by doyourclanwars** [comment]
same

**Comment by theyareonit** [comment]
![image](https://github.com/theyareonit/Click-Between-Frames/assets/82268986/219cf122-554c-43ff-b724-755249ba46a3)

**Comment by aguyi** [comment]
uh i used the keys button, and i NEVER saw anything with the label "click between frames" plus i cant find anything similar to click between frames

**Comment by theyareonit** [comment]
you just use the normal p1/p2 jump keybinds
