### ISSUE TITLE
Buffer clicks seem to be messed up

### ISSUE THREAD

**Issue by Fornax985** [theyareonit/Click-Between-Frames#11]
https://twitter.com/LcKiThink/status/1778809567708590551
Referring to this part of Tartarus, it's a couple of buffer clicks in a row and with this mod it's almost impossible to pass the last click

**Comment by Fornax985** [comment]
unless you turn on physics bypass and set a higher framerate, then it becomes consistently passable again

**Comment by theyareonit** [comment]
i believe this is fixed in v1.1.0

**Comment by theyareonit** [comment]
actually nvm this might not be entirely fixed, will continue to look into it

**Comment by theyareonit** [comment]
should be fixed for real in 1.1.2

**Comment by Fornax985** [comment]
Ahahaha let's go
