### ISSUE TITLE
Mac support?

### ISSUE THREAD

**Issue by FireDasher** [theyareonit/Click-Between-Frames#12]
Please add mac support I dont have a windows

**Comment by theyareonit** [comment]
camila314 is working on it

**Comment by FireDasher** [comment]
ok good I hope mac support is out soon

**Comment by FireDasher** [comment]
Still waiting...

**Comment by theyareonit** [comment]
¯\_( ツ )_/¯ not in my control

**Comment by FireDasher** [comment]
2.206 is out and now geode is broken :(
And was camila314 even working on it??

**Comment by theyareonit** [comment]
she was working on it but she seems to have stopped, youll have to use the Click on Steps mod instead (once it's updated for 2.206)
