### ISSUE TITLE
Mobile support?

### ISSUE THREAD

**Issue by VeensCal** [theyareonit/Click-Between-Frames#13]
Pls add mobile support I don't have a pc

**Comment by theyareonit** [comment]
coming eventually

**Comment by VeensCal** [comment]
Android 32 and Android 64

**Comment by Kurayami8df** [comment]
Plis

**Comment by Idkwhattoputformyusername** [comment]
Why is it taking forever?😭😭

**Comment by theyareonit** [comment]
download the click on steps mod by zmx, it works on android and is similar to this mod

**Comment by theyareonit** [comment]
i was never working on the android port myself, it was camila314 but i think she's lost interest on it so i doubt it will happen

**Comment by Idkwhattoputformyusername** [comment]
> i was never working on the android port myself, it was camila314 but i think she's lost interest on it so i doubt it will happen

Noooooooooo

**Comment by rV4nxZ** [comment]
> i was never working on the android port myself, it was camila314 but i think she's lost interest on it so i doubt it will happen

then camila314 just betrayed Android users?
