### ISSUE TITLE
percentages are not displayed correctly

### ISSUE THREAD

**Issue by free4010** [theyareonit/Click-Between-Frames#14]
if you turn on Physics Bypass together with CBF, for example at 720 fps, then the percentages after death and the record itself at the level will be displayed incorrectly
![image](https://github.com/theyareonit/Click-Between-Frames/assets/157967674/58a24ed5-a46c-49ce-b7aa-047c396c2172)

my downloaded mods
![image](https://github.com/theyareonit/Click-Between-Frames/assets/157967674/7dd00e8a-9872-4553-8237-735db2802c6d)

and mhv8 settings
![image](https://github.com/theyareonit/Click-Between-Frames/assets/157967674/ced3c3e1-713f-4f26-820a-d93e5e7872c6)

**Comment by theyareonit** [comment]
This is due to percentages in 2.2 being based on the number of physics steps rather than the player's position (I think)

**Comment by free4010** [comment]
this bug is not caused by your mod, it's a bug mhv8 physics bypass
your mod is cool😎
