### ISSUE TITLE
Inevitable crash when trying to play an online level

### ISSUE THREAD

**Issue by LaylinYo** [theyareonit/Click-Between-Frames#2]
Can't even actually open the level's menu screen n shit bc it instantly crashes lol

2024-04-08T18:38:22+0300
Whoopsies! An unhandled exception has occurred.
It appears that the crash occurred while executing code from the "syzzi.click_between_frames" mod. Please submit this crash report to its developers (syzzi) for assistance.

== Geode Information ==
Loader Version: v2.0.0-beta.23
Loader Commit: b3c0c9f
Bindings Commit: a4c775b
Installed mods: 39
Problems: 0

== Exception Information ==
Faulty Module: D:\Programs\Steam\steamapps\common\Geometry Dash\geode\unzipped\syzzi.click_between_frames\syzzi.click_between_frames.dll
Faulty Mod: syzzi.click_between_frames
Exception Code: c0000005 (EXCEPTION_ACCESS_VIOLATION)
Exception Flags: 0
Exception Address: 568052F6 (syzzi.click_between_frames.dll + 52f6)
Number Parameters: 2

== Stack Trace ==
 - D:\Programs\Steam\steamapps\common\Geometry Dash\geode\unzipped\syzzi.click_between_frames\syzzi.click_between_frames.dll + 52f6
 - 04501ED7
 - D:\Programs\Steam\steamapps\common\Geometry Dash\geode\unzipped\zilko.xdbot\zilko.xdbot.dll + 43a6
 - 04501ED7
 - 16A83049
 - 16A82C6B
 - D:\Programs\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 3c12d8
 - D:\Programs\Steam\steamapps\common\Geometry Dash\Geode.dll + 172764 (gdMainHook + 532 | D:\a\geode\geode\loader\src\platform\windows\main.cpp:59)
 - D:\Programs\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 3c267e
 - C:\WINDOWS\System32\KERNEL32.DLL + 17ba9 (BaseThreadInitThunk + 25)
 - C:\WINDOWS\SYSTEM32\ntdll.dll + 6bdab (RtlInitializeExceptionChain + 107)
 - C:\WINDOWS\SYSTEM32\ntdll.dll + 6bd2f (RtlClearBits + 191)

== Register States ==
EAX: 00000000
EBX: 00000041
ECX: 1f7ca7b0
EDX: 00ed67ec
EBP: 004ff340
ESP: 004ff308
EDI: 13b1c712
ESI: 00000000
EIP: 568052f6

== Installed Mods ==
x | [v8.0.0-alpha.134] absolllute.megahack
x | [v1.0.1] alphalaneous.transparent_lists
x | [v1.0.1] asaki_zuki.same_dual_color
x | [v1.0.6] bitz.customprofiles
x | [v1.0.2] blueblock6.cleanstartpos
  | [v1.0.0] capeling.colored_level_info_bg
  | [v1.0.3] cdc.level_thumbnails
  | [v1.5.1] coopeeo.customname
  | [v4.0.0] cvolton.betterinfo
x | [v1.1.2] cvolton.misc_bugfixes
x | [v1.0.1] elnexreal.auto_priority
  | [v1.0.3] elsai.brightness_mod
  | [v2.2.0] fleym.nongd
  | [v1.2.16] gdutilsdevs.gdutils
x | [v1.5.2] geode.custom-keybinds
x | [v2.0.0-beta.23] geode.loader
x | [v1.8.1] geode.node-ids
  | [v6.2.0] hjfod.betteredit
x | [v1.0.5] hjfod.gdshare
x | [v1.0.5] hjfod.gmd-api
x | [v0.2.0] kevadroz.nocontrollerglyphs
  | [v1.1.3] mat.circle-tool
  | [v1.0.0] mat.reference-image
x | [v1.1.0] mat.scroll-zoom
  | [v1.0.1] relative.advanced_song_search
x | [v1.1.2] relative.mininextfree
  | [v1.2.0] shineua.geometrize2gd
x | [v1.0.2] slammy333.save_button
x | [v1.0.5] sofabeddd.colored_icon_kit
x | [v1.0.2] syzzi.click_between_frames
x | [v2.10.2] techstudent10.discord_rich_presence
x | [v1.1.0] thesillydoggo.better_startpos_menu
  | [v1.6.9] thesillydoggo.entersearch
  | [v2.1.0] TheSillyDoggo.GradientPages
x | [v1.2.0] thesillydoggo.moretags
x | [v1.6.8] tpdea.betterpause-Better
  | [v3.0.0] user95401.profile_image
x | [v1.0.1] xiyxs.confirmpracticerestart
x | [v1.5.3] zilko.xdbot

**Comment by LaylinYo** [comment]
Found mod incompatibility with [v1.2.0] thesillydoggo.moretags. Upon deletion of the mod there were no more instant crashes.

**Comment by theyareonit** [comment]
fixed in https://github.com/theyareonit/Click-Between-Frames/commit/bebf844c86c63bb1429ae9520934b58263be3104
thank you for the report
