### ISSUE TITLE
CBF not available?

### ISSUE THREAD

**Issue by ChezBorgerr** [theyareonit/Click-Between-Frames#23]
Got geode 3.0.0 alpha.2, searched for CBF using "CBF" "click" and couldn't find it. Also, i placed the .geode file (latest one) in C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\mods, reloaded GD, and it said there was an error. I clicked show errors only, and the mod didn't even show up.

Is there a way you can add CBF to geode, or make the .geode file work for geode 3.0.0?

**Comment by theyareonit** [comment]
The mod should be updated for GD 2.206 within a few days.
