### ISSUE TITLE
Why is p2 jumping midair??

### ISSUE THREAD

**Issue by irscy** [theyareonit/Click-Between-Frames#24]
It's a CBF-specific issue. I've tried to fix it by enabling always limit controls, disabling/enabling p2 input but nothing's worked

**Comment by irscy** [comment]
![image](https://github.com/theyareonit/Click-Between-Frames/assets/47720070/398f4ea7-8e7f-4db8-afe5-01741a8da4ea)
I should probably include an image

**Comment by theyareonit** [comment]
this is fixed in v1.1.4, just update it
