### ISSUE TITLE
Moving objects sometimes not moving properly.

### ISSUE THREAD

**Issue by S4ndst0ne** [theyareonit/Click-Between-Frames#26]
So I was playing Ruler of Everything with Click Between Frames, and the moving platform that you stand on in the very beginning was behaving very weirdly. It was slightly struggling to catch up with the player, and would randomly fling me upwards. When I disabled Click Between Frames, the moving platform was behaving normally. There are two move triggers for this platform, one locks the platform's position to the Player X, while the other moves the platform up 200 units in the span of 15 second without any easings.

**Comment by theyareonit** [comment]
this is fixed in 1.1.8

**Comment by S4ndst0ne** [comment]
Thank you.
