### ISSUE TITLE
Better cheat indicator

### ISSUE THREAD

**Issue by CuteistFox** [theyareonit/Click-Between-Frames#27]
Im thinking something like zbots 940 pixels of falling into deep space(uk), but instead of using the 940 pixels standard for macros, useing soemthing more than 1004 pixels on the level complete text. This is because the "CBF" at the top on the level complete screen is sometimes annoying.

**Comment by theyareonit** [comment]
I did try adding a fade-in to the indicator but it looked kinda ugly and was even more distracting. Maybe I could make it more transparent? And maybe add an option to control which corner of the screen the indicator shows up in.

**Comment by CuteistFox** [comment]
Oh yeah, i forgot about forking
