### ISSUE TITLE
CBF-Only death with wave 

### ISSUE THREAD

**Issue by Crooozy** [theyareonit/Click-Between-Frames#29]
When releasing an input on a downwards-moving tight corridor with D-blocks as mini wave, you die where you would not in vanilla.

I have made a clip of this with vanilla for comparison.
https://youtu.be/wMZ18CU2cC0

You can also test it in this level
106875809

This bug is consistent and has been happening since at very least v1.1.12 but I believe it has been happening since initial release.

**Comment by theyareonit** [comment]
Probably caused by the fact that the mod does an extra collision check when you make an input, but doesn't update the positon of moving objects between frames, so you can clip into them in some situations.
