### ISSUE TITLE
Cant use numpad buttons as jump keybinds

### ISSUE THREAD

**Issue by functionxd** [theyareonit/Click-Between-Frames#3]
Not an urgent issue but i like using numpad1 as my jump keybind and it doesn't work when i have this mod

**Comment by theyareonit** [comment]
Are you unable to set numpad buttons as keybinds in the custom keybinds menu? Or do they just not work in levels?

**Comment by functionxd** [comment]
it lets me set them but they dont work ingame

**Comment by gGhostly** [comment]
please fix this i only ever use numpad 5, thanks

**Comment by Rylika** [comment]
As a Numpad user as well for playing platformer having hands further apart for 2player levels and or moving with 1 hand and the other being jump. Have the exact same problem.

without mod
https://github.com/theyareonit/Click-Between-Frames/assets/74024949/a6497dd4-f365-427d-b4b0-0cafe06702cd

mod on
https://github.com/theyareonit/Click-Between-Frames/assets/74024949/0c6bc0dd-df6d-414a-9875-881fd2969dac

**Comment by zMilenka** [comment]
There seems to be no fix but you can try remapping the numpad keys with the non-numpad keys which seems to work

**Comment by theyareonit** [comment]
fixed in v1.1.16 (requires num lock to be enabled)
