### ISSUE TITLE
CBF not working correctly with moving platforms

### ISSUE THREAD

**Issue by Robi0990** [theyareonit/Click-Between-Frames#32]
If you jump on moving platforms it gives you way too much momentum than usual sometimes. This does not happen on CBF v1.0.9. An example of where this happens is on Limbo at 83%. 

First video showcases the bug on 2.206 and CBF v1.1.15 and second one shows how it normally behaves in 2.204 and CBF v1.0.9.

https://github.com/theyareonit/Click-Between-Frames/assets/67930895/9b1e318e-2b13-41df-a3ae-bd07d78bd26a

https://github.com/theyareonit/Click-Between-Frames/assets/67930895/122e49c3-2a79-47d0-99bd-f3db4198c186

**Comment by S4ndst0ne** [comment]
I got something similiar in Ruler of Everything.

**Comment by S4ndst0ne** [comment]
I am on the latest version too. ^^^

**Comment by S4ndst0ne** [comment]
Even after I updated CBF sometimes when I play Ruler of Everything in the beginning the moving platform will randomly fling me upwards.

**Comment by obj-obj** [comment]
I also have delayed inputs sometimes on moving platforms

**Comment by theyareonit** [comment]
should be fixed in v1.1.16
