### ISSUE TITLE
strange move bug

### ISSUE THREAD

**Issue by Lanalanita** [theyareonit/Click-Between-Frames#36]
this bug happens when you have in a moving platform, causes the player to ascend in an abnormal and illogical way

specifically if the platform moves up (or down in inverted gravity)

https://github.com/theyareonit/Click-Between-Frames/assets/108598436/7563c34c-f8c5-4647-8924-90c5c4f0ea1e

**Comment by SorkoPiko** [comment]
I also have this issue. It happens all the time in normal gameplay. Please fix this as soon as possible.

**Comment by JerichoGesolgani** [comment]
This happended to me in congregation where sometimes this bs happended thank im not the only one

**Comment by theyareonit** [comment]
should be fixed in v1.1.16
