### ISSUE TITLE
click-between-frames does not work on mac and Android

### ISSUE THREAD

**Issue by Thinkseal** [theyareonit/Click-Between-Frames#37]
if you are on a mac or android device you can't use click-between-frames as it has not been ported yet. can click-between-frames please be ported to macOS and android since a significant amount of players use android and like 2 use macOS.

**Comment by Thinkseal** [comment]
nooooooooo :( (can you at least make it work on Linux?)

**Comment by theyareonit** [comment]
> nooooooooo :( (can you at least make it work on Linux?)

It should work on Linux, see the discussion here if you're having issues: https://github.com/theyareonit/Click-Between-Frames/issues/63

**Comment by Thinkseal** [comment]
Thanks
