### ISSUE TITLE
Using CBF sometimes jump extraordinary high in moving object

### ISSUE THREAD

**Issue by JerichoGesolgani** [theyareonit/Click-Between-Frames#41]
As you see in the title sometimes using click between frames there a RNG Bug where sometimes my icon/robot jump extremely high in moving object, this started happended to me yesterday where i play the level "Congregation" i play that just for improves the timing skill not for the memes. But in 44% as the object is heavily relies on moving platforms/object  there is like 25% chance to my icon to jump like a jumphack this also aplies with robot as well as it sometimes jump like jumphack. How the fuck i supposed to play congregation without bother with this rng shit bug again?!?! I not sure if this CBF Bug or Vanilla bug. Syzzi if you read this thanks but hopefully the way i saying is good enought to understand. I have no video evidence but good writhing is enought.

**Comment by theyareonit** [comment]
should be fixed in v1.1.16
