### ISSUE TITLE
something happening with slopes

### ISSUE THREAD

**Issue by Rafasvames** [theyareonit/Click-Between-Frames#42]
sometimes when i jump on slopes using the ufo or the robot my icon just teleports up, and when i disabled cbf it stoped, maybe it could be a problem idk

**Comment by LoicBurri-Rochon** [comment]
I've had the same issue as well. see ethereal artifice at 29~30% when you jump off the slope you just fly into the ceiling. I know there was a fix for something similar in a recent update but I guess it's different with slopes

**Comment by theyareonit** [comment]
should be fixed in v1.1.19, please test

**Comment by theyareonit** [comment]
nvm im dumb, update fixed downward slopes but broke upward slopes in the process

**Comment by theyareonit** [comment]
should be fixed for real now in v1.1.20
