### ISSUE TITLE
Some variant of the moving platform bug still exists in v1.1.18

### ISSUE THREAD

**Issue by obj-obj** [theyareonit/Click-Between-Frames#43]
https://github.com/theyareonit/Click-Between-Frames/assets/57120300/8b8f8925-c5e2-48cb-905a-b7d0cca4b340

Possibly a duplicate of #42?

**Comment by Oftacom** [comment]
Same problem

**Comment by K1mer0** [comment]
Congregation is literally impossible

https://github.com/theyareonit/Click-Between-Frames/assets/175163780/5024c510-cd80-4217-8024-fd8073ce41bd

**Comment by theyareonit** [comment]
probably fixed in v1.1.19, please test

**Comment by theyareonit** [comment]
nvm im dumb, update fixed downward slopes but broke upward slopes in the process

**Comment by theyareonit** [comment]
should be fixed for real now in v1.1.20
