### ISSUE TITLE
CBF does not affect keyboard input on Linux

### ISSUE THREAD

**Issue by voiding-0** [theyareonit/Click-Between-Frames#44]
On Linux, CBF works for mouse but not for keyboard. I am unsure what exactly causes this.

Demonstration (very cringe video): [https://youtu.be/qJ9eePGnQe4](url)

I am running the Windows version of the game using Proton. I have tried switching Proton versions but nothing works.
I have also tried disabling all other geode mods to ensure there is no conflict happening, and the issue persists.

**Comment by theyareonit** [comment]
Does this also happen on Wine alone (not Proton)? Also, are you on Wayland or xorg?

**Comment by theyareonit** [comment]
for now, ig just bind a key to mouse input if you can

**Comment by voiding-0** [comment]
> Does this also happen on Wine alone (not Proton)? Also, are you on Wayland or X11?

I can't seem to run GD at all with Wine, it only works with Proton. I am on Wayland.

**Comment by rV4nxZ** [comment]
try x11

**Comment by theyareonit** [comment]
It's broken on Xorg too. It's a bug in Wine. I will have a workaround in the next release.

**Comment by SafilentLVC73778** [comment]
Hi. I registered on github specifically to report that after a recent update(1.2.1) I have input stopped working on linux ubuntu(The cube jumps if only pressed at the beginning of the level and not released until the end*). Latest version, X11, using proton to run GD. Thanks for your attention.

**Comment by theyareonit** [comment]
@SafilentLVC73778 Try adding yourself to the `input` group with `sudo usermod -aG input $USER`. If that does not work, then send a log (`[GD.exe Folder]/geode/logs`).

Also, this is a bug report for an unrelated issue, which has now been fixed. Please keep further discussion here instead: https://github.com/theyareonit/Click-Between-Frames/issues/63
