### ISSUE TITLE
slope bugs (MORE)

### ISSUE THREAD

**Issue by my234mon** [theyareonit/Click-Between-Frames#46]
whenever your the robot (or atleast the mini) sometimes on less steep slopes you cant jump

**Comment by theyareonit** [comment]
Can you name a specific level where this happens? And the % in the level as well.

**Comment by my234mon** [comment]
ive noticed that it happens on the robot jumps on the 20% robot in scream machine (some jumps more than others)

**Comment by theyareonit** [comment]
should be fixed as of 1.2.0
