### ISSUE TITLE
Weird double click bug

### ISSUE THREAD

**Issue by Bodysz** [theyareonit/Click-Between-Frames#48]
I don't know EXACTLY how this bug works but it is only possible with cbf.
https://clips.twitch.tv/VibrantNaiveAsteriskPastaThat-RHC_kh0gUCidEeaL

**Comment by JerichoGesolgani** [comment]
This not cbf issue, this is mostly likely your input device (mouse/mice, keyboard or etc.) is started double clicking

**Comment by theyareonit** [comment]
Fixed in v1.1.21
