### ISSUE TITLE
weird double jump

### ISSUE THREAD

**Issue by Yaxisq** [theyareonit/Click-Between-Frames#50]
idk how this happens the only mode that effects the gameplay that i have on is cbf
[Geode 2024-07-29 22.15.07.log](https://github.com/user-attachments/files/16420435/Geode.2024-07-29.22.15.07.log)
[https://www.youtube.com/watch?v=9rwI9HNvULk](url)

**Comment by theyareonit** [comment]
Can you give more detailed steps to reproduce the bug? E.g. which inputs you're using, the exact sequence of inputs youre doing (e.g. hold space -> wait until right after you jump -> press up arrow -> release space). I can't get the issue to happen even once on my PC.

**Comment by theyareonit** [comment]
Fixed in v1.1.21
