### ISSUE TITLE
question: what is thread priority? and do i need it on for better performance and percision

### ISSUE THREAD

**Issue by JerichoGesolgani** [theyareonit/Click-Between-Frames#52]
title said it all

**Comment by theyareonit** [comment]
It determines whether or not the part of CBF that listens for inputs should have priority over the rest of GD's code. Enabling it should increase input precision, but may cause minor lag in some cases.

**Comment by JerichoGesolgani** [comment]
> It determines whether or not the part of CBF that listens for inputs should have priority over the rest of GD's code. Enabling it should increase input precision, but may cause minor lag in some cases.

That good but bad thing is that why it could cause some minor lag in certain cases why?

**Comment by theyareonit** [comment]
Because if the input thread has higher priority than the game itself, then when you make inputs it could take time away from the game's main thread in some cases.

**Comment by JerichoGesolgani** [comment]
> Because if the input thread has higher priority than the game itself, then when you make inputs it could take time away from the game's main thread in some cases.

Wait so the game can lag just micro a bit dues cbf taking the thread priority over. Does this means that regardless how powerful you device (e.g. better cpu/gpu) is, it will still lag or it would be **Extremely** little (like microsecond) on hugher end device like gaming pc/laptop

**Comment by theyareonit** [comment]
It should only be a few microseconds on a strong PC, yes.
