### ISSUE TITLE
CBF not working properly for me?

### ISSUE THREAD

**Issue by maxguy56** [theyareonit/Click-Between-Frames#58]
I dont know how to quite describe it. On my old PC whenever i used to rapidly click my wave icon went more up than it went down. Same thing with ship. Now its the opposite, it goes down more than it does up. The clicks dont feel instant. I cant figure wether its my operating system or graphics card being the problem. Other than that im using the same mouse and monitor as i've always been using when it worked.

Heres a video link:

https://streamable.com/hmn0r8

**Comment by maxguy56** [comment]
Any help would be appreciated

**Comment by theyareonit** [comment]
Did you test without CBF too?

**Comment by maxguy56** [comment]
Yep heres a recording of me having it turned off. No difference.

https://streamable.com/8j8muk

I would like to mention that i recently switched from Windows 10 to 11, So i don't know if anything changed there.

**Comment by theyareonit** [comment]
Well, if the issue is there even without CBF, then it's definitely not a CBF bug.

**Comment by maxguy56** [comment]
Do you think its a compatibility issue?

**Comment by theyareonit** [comment]
I wouldn't know.
