### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by EESports7** [theyareonit/Click-Between-Frames#6]
Looking at explanations for this mod, I would like to know the difference between this mod and the draw divide method.

**Comment by theyareonit** [comment]
Draw divide works by running a high number of frames on the CPU, but only rendering out a portion of them, which reduces the GPU's workload.

This mod works by splitting the physics calculation steps on each frame into smaller "sub-steps" whenever you input, and inserting the input in between those sub-steps. 

It causes significantly less lag than Draw Divide, for two reasons:
1. The game only does extra work on frames where you make an input
2. The only extra work that is done on frames where you click is physics calculations, which aren't very performance intensive. Draw Divide, however, does the entire process of creating a frame except for the rendering.
