### ISSUE TITLE
The game ignores "right click as primary button" setting when using CBF

### ISSUE THREAD

**Issue by ExtremeGD** [theyareonit/Click-Between-Frames#61]
![wrsthudhkiu](https://github.com/user-attachments/assets/1408d70e-7f01-4816-9859-a445394af2a7)

I have right click set as my primary mouse button in windows settings, which means left and right click are swapped, and in vanilla GD I use right click.

But with CBF enabled, the game only registers left click as an input regardless of the setting being on.

It only registers right click as an input with the right click p2 option enabled but it still uses it for p2 despite of the windows setting.

**Comment by theyareonit** [comment]
Use the right click p2 setting in CBF and then the swap 2p controls option in GD's settings
