### ISSUE TITLE
question: what is "Don't submit CBF completions on star levels to leaderboards"

### ISSUE THREAD

**Issue by JerichoGesolgani** [theyareonit/Click-Between-Frames#64]
does this means i'm forbidden to complete/beat any rated level or i just completed a star rated but i dont check the leaderboard nor press/click the leaderboard button?

**Comment by natsuyuchn** [comment]
This means any completion with CBF enabled won't be submitted to leaderboards. CBF is banned from official leaderboards because RobTop himself doesn't like CBF being used, so any completion with CBF submitted to it, will get you banned

**Comment by natsuyuchn** [comment]
in other words, this prevents you from being banned while using cbf on rated levels

**Comment by JerichoGesolgani** [comment]
> in other words, this prevents you from being banned while using cbf on rated levels

what so strange is that, im been using cbf since its release and i been using on some rated levels cuz im bored af but however i never get banned (im on 12798 place on global leaderboard i have 13k+ stars) so how does this make sense?

**Comment by theyareonit** [comment]
> in other words, this prevents you from being banned while using cbf on rated levels

It doesn't prevent you from getting banned, since you still get stars. It just means that it won't submit records to the Weekly/All Time/Friends leaderboards.

**Comment by JerichoGesolgani** [comment]
> It doesn't prevent you from getting banned, since you still get stars. It just means that it won't submit records to the Weekly/All Time/Friends leaderboards.

i have quite good amount of star and still i dont get banned in the leaderboard or maybe because im not high on the leaderboard to get banned for cbf (note: again i dont use cbf's physics bypass as i play on 60fps)
