### ISSUE TITLE
It doesn't work properly left handed

### ISSUE THREAD

**Issue by totolgueimer** [theyareonit/Click-Between-Frames#65]
For some reason it partially works with left handed mouse, sometimes it captures the input, but works perfectly right handed
https://github.com/user-attachments/assets/4ffa8c71-a792-45dc-9fa3-4646c1a01c85

**Comment by totolgueimer** [comment]
A temporary workaround is to activate right click p2

**Comment by theyareonit** [comment]
The mod has no way to detect any changes to button bindings in software; you have to rebind at either the hardware or firmware level. So, the right click p2 option is your only choice.
