### ISSUE TITLE
no inputs registering on linux

### ISSUE THREAD

**Issue by Eaglerider70** [theyareonit/Click-Between-Frames#67]
so before cbf updated to the version where it "fixed linux support" it just broke it, now I can't play levels with cbf because no clicks register in the new update, I tried changing proton versions but that didnt help

**Comment by Eaglerider70** [comment]
basically when I click on linux, it does the same it would do with a controller

**Comment by ezra-351** [comment]
does the build linked in this comment work for you?
https://github.com/theyareonit/Click-Between-Frames/issues/63#issuecomment-2365055674

**Comment by Eaglerider70** [comment]
nope

**Comment by Eaglerider70** [comment]
I'm having the exact same issue you had, I'm also using arch and that happens when I click

**Comment by Eaglerider70** [comment]
> does the build linked in this comment work for you? [#63 (comment)](https://github.com/theyareonit/Click-Between-Frames/issues/63#issuecomment-2365055674)

hold up, that is the latest version of cbf, thats the build I was just using

**Comment by Eaglerider70** [comment]
I just switched to 1.1.21 and now it works, it seems 1.2.0 and 1.2.1 broke linux, even though syzzi tried to "fix linux"

**Comment by ezra-351** [comment]
it's different, just has the same version label because it's not a release and was just made to test something, but it made the difference on my end.

logs might be useful to have, add `PROTON_LOG=1` to the start of your launch options and look for issues in the steam-322170.log file that gets made in your home folder, or upload it if you can't tell.

**Comment by theyareonit** [comment]
> it seems 1.2.0 and 1.2.1 broke linux

Keyboard input didn't work on Linux before 1.2.0, and mouse input was less precise than it is now.

@Eaglerider70 Have you added yourself to the `input` group? `sudo usermod -aG input $USER`

**Comment by Eaglerider70** [comment]
> > it seems 1.2.0 and 1.2.1 broke linux
> 
> Keyboard input didn't work on Linux before 1.2.0, and mouse input was less precise than it is now.
> 
> @Eaglerider70 Have you added yourself to the `input` group? `sudo usermod -aG input $USER`

yeah I did

**Comment by Eaglerider70** [comment]
> > it seems 1.2.0 and 1.2.1 broke linux
> 
> Keyboard input didn't work on Linux before 1.2.0, and mouse input was less precise than it is now.
> 
> @Eaglerider70 Have you added yourself to the `input` group? `sudo usermod -aG input $USER`

I did that now and it works, ty
