### ISSUE TITLE
No inputs working on Linux (Pop!_OS latest)

### ISSUE THREAD

**Issue by SaddBoie** [theyareonit/Click-Between-Frames#68]
I've seen this issue reported here before, and I've tried adding myself to the input group already, that hasn't worked. I've also tried changing `#!/bin/sh` to `#!/bin/bash` at the top of the linux-input.exe file (also didn't work). I'm also running a fresh install of both Pop!_OS and GD so I've got absolutely no clue what could be causing it.

**Comment by theyareonit** [comment]
Try the build at the bottom of this link: https://github.com/theyareonit/Click-Between-Frames/issues/63

**Comment by SaddBoie** [comment]
Yeah that's still not working

**Comment by SaddBoie** [comment]
And changing /sh to /bash in the same file doesn't work either, forgot to mention that

**Comment by theyareonit** [comment]
Please send Steam/Geode logs as described in that issue, then.

**Comment by SaddBoie** [comment]
Sorry where do I find the logs?

**Comment by theyareonit** [comment]
Geode logs are in `[GD.exe folder]/geode/logs`
Not sure exactly how to get Steam logs tbh I never found out how (I usually just run GD directly through Wine), you'll have to Google

**Comment by SaddBoie** [comment]
[Geode 2024-09-28 00.39.27.log](https://github.com/user-attachments/files/17171500/Geode.2024-09-28.00.39.27.log)
![image](https://github.com/user-attachments/assets/ec3fa8fd-b480-43e3-bff8-3c75a3056fce)

I got the GD logs, but I'm not sure about the Steam ones. I ran `cd ~/.steam/steam/logs` to generate that terminal interface btw

**Comment by SaddBoie** [comment]
I have to select one of those logs, but there's no indication on which I should be looking at

**Comment by theyareonit** [comment]
Your Geode log indicates that linux-input.exe.so apparently "is not a valid Win32 application." Have you tried with different Proton versions? Also, is there anything weird about your GD installation? (e.g. is it installed on an NTFS drive? Is it in a different folder than usual? Or anything else that you think could be notable)

**Comment by SaddBoie** [comment]
![image](https://github.com/user-attachments/assets/611beaaf-bad7-4c3d-9790-d8cd9176e2ee)

Not sure what this means exactly but here's my drive list

**Comment by SaddBoie** [comment]
Also I'm pretty sure my installation isn't in a different folder, as I just used the default settings when installing everything

**Comment by SaddBoie** [comment]
Any updates? I tried a clean install of the config files (with and without the build you suggested) and still no luck. How am I so unfortunate with this man

**Comment by CJoshuawImNotADev** [comment]
im on antix linux debian 12 bookworm and the last update broke my input too, i think im downgrading rn

**Comment by theyareonit** [comment]
@SaddBoie Was that Geode log on the officially released version? Or was it on the build that I posted in the GitHub issue? Also again, I really have no idea where to get Steam game logs. I can't even get GD to start through Steam, so I wouldn't be able to tell you.

@CJoshuawImNotADev Try the build at the bottom of this page: https://github.com/theyareonit/Click-Between-Frames/issues/63; also make sure to add yourself to the input group with `sudo usermod -aG input $USER`

**Comment by theyareonit** [comment]
@Krepppa352 That shouldn't be related to your problem. Disabling Custom Keybinds is probably just disabling CBF too. It's almost certainly a CBF bug. Have you tried using different input methods (i.e. mouse)?

**Comment by Krepppa352** [comment]
@theyareonit yes, I've tried all input keys. But the `sudo usermod -aG input` seems to work, I've been told to do that in a different issue as well.

**Comment by CJoshuawImNotADev** [comment]
@theyareonit I've tried the input group method and it doesn't work
I tried the #!/bin/bash method and it doesn't work
I also tried installing protontricks and run the protontricks command in the thread `protontricks-launch --appid 322170 linux-input.exe.so` 
and it just crashes, here is the full terminal output 
[untitled.txt](https://github.com/user-attachments/files/17179699/untitled.txt)


this is how my `groups` command looks like, I don't know if there is anything wrong
![image](https://github.com/user-attachments/assets/de7b8c93-0169-4209-83ed-b5f22c08ffa0)

**Comment by r1input** [comment]
[Geode 2024-09-29 14.07.02.log](https://github.com/user-attachments/files/17181333/Geode.2024-09-29.14.07.02.log)
also experiencing this issue. tried the modified build listed, changed sh to bash, and added myself to the input group, but no luck. from what i can see in my logs, it seems that the linux input program just fails to start completely?
`14:07:06 INFO  [M>] [Click Betwee>]: Wine Linux`
`14:07:06 ERROR [M>] [Click Betwee>]: Failed to launch Linux input program: 193`

**Comment by Eaglerider70** [comment]
have you tried adding yourself to the input group?

**Comment by theyareonit** [comment]
There's an update out now, tell me if it makes any difference.

**Comment by SafilentLVC73778** [comment]
I have addressed this problem before, thank you for paying attention to it. Alas, there is no change on uhuntu. Although I don't know much about linux and there is a possibility that the problem is in the PC and not in the mod. Anyway CBF v1.1.19 works, so bandaid fix for upward slopes in v1.1.20 somehow affected linux. What do you think?

**Comment by theyareonit** [comment]
@SafilentLVC73778 The slope change is unrelated, the breaking on Linux comes from the fact that I changed the way input on Linux works in v1.2.0 (since it didn't work properly at all in previous updates).

**Comment by theyareonit** [comment]
It seems like everyone with issues is on a Debian based distro, so that's probably related. I'll try to see if I can fix it.

**Comment by xEndLevel** [comment]
Try with gamescope possibly? haven't seen that mentioned here yet

**Comment by fbfnysnshnsgnwg** [comment]
inputs either fail, or it acts like you are constantly holding (linux mint, proton experimental, latest cbf)
