### ISSUE TITLE
laptop keyboard quesions

### ISSUE THREAD

**Issue by JerichoGesolgani** [theyareonit/Click-Between-Frames#76]
does this mod on a laptop keyboard just as good (windows btw) as 8000hz gaming keyboard or smth as i dont know how this mod work with laptop keyboard when they do not have polling rate (even for gaming laptop) instead they have real-time response time or maybe i confused about laptop keyboard as i am laptop user and because of it, if i searchs "How to change laptop keyboard polling rate" and all the result is just change mechanical keyboard polling rate even tho it has the word "laptop" to it. so how does this mod work with laptop keyboard?

**Comment by theyareonit** [comment]
Your laptop keyboard's responsiveness has nothing to do with CBF. Your keyboard could be good, or it could be bad, I wouldn't know. The mod has no control over your keyboard.

All CBF does is make the game continuously check for inputs rather than only checking for inputs at the start of a frame (simplified explanation).

**Comment by JerichoGesolgani** [comment]
> Your laptop keyboard's responsiveness has nothing to do with CBF. Your keyboard could be good, or it could be bad, I wouldn't know. The mod has no control over your keyboard.
> 
> All CBF does is make the game continuously check for inputs rather than only checking for inputs at the start of a frame (simplified explanation). It cannot make a specific keyboard better or worse than it otherwise would be, relative to other keyboards.

so does this means regardless of how bad laptop keyboard is (i use lenovo ideapad keyboard if you to know) it should do well or something, also is it possible to test the PS/2 protocol polling rate as the keyboard polling test in online is mostly pressing the keys the earilest as you can which i extremely hated that i tried use some software none of them show the true result. So is here the thing, is it safe to adjust the "KeyboardDataQueueSize" in the registery editor and disable high precision event timer in the device manager for the best performance and lowest that i wanted. Oh yeah i btw my drive is "Standard PS/2 Keyboard" and so. Is it possible to adjust the polling/scan rate of the PS/2 Protocol i heard that there a firmware but idk where can i do that i feel in stuck rn as there is not much i can do to make my lenovo ideapad keyboard to feel so instant.

**Comment by theyareonit** [comment]
> so does this means regardless of how bad laptop keyboard is [...] it should do well or something

It means that it will do the same as it would without CBF. If it was bad before, it'll still be bad with CBF. If it was good before, it'll still be good with CBF. The mod has no effect on your keyboard, it only affects the game itself.

> is it possible to test the PS/2 protocol polling rate

PS/2 is interrupt based, and doesn't have a fixed polling rate for keyboards (i.e. it's effectively "infinite" polling rate unless you're sending multiple inputs in quick succession). This doesn't automatically make your keyboard good in terms of input lag though, there are more factors than just polling rate that influence how well a keyboard performs (debouncing, scan rate, general firmware quality, etc.).

> KeyboardDataQueueSize

Changing this can cause dropped inputs with basically 0 input lag improvement. I wouldn't recommend it.

> disable high precision event timer in the device manager

This does nothing, you have to disable it through a different method. I won't say what that method is though, because it hurts performance on newer windows versions (it can only improve performance on very outdated versions of Windows 10).

> i feel in stuck rn as there is not much i can do to make my lenovo ideapad keyboard to feel so instant.

Buy a SayoDevice O3C from AliExpress.

**Comment by JerichoGesolgani** [comment]
> > so does this means regardless of how bad laptop keyboard is [...] it should do well or something
> 
> It means that it will do the same as it would without CBF. If it was bad before, it'll still be bad with CBF. If it was good before, it'll still be good with CBF. The mod has no effect on your keyboard, it only affects the game itself.
> 
> > is it possible to test the PS/2 protocol polling rate
> 
> PS/2 is interrupt based, and doesn't have a fixed polling rate for keyboards (i.e. it's effectively "infinite" polling rate unless you're sending multiple inputs in quick succession). This doesn't automatically make your keyboard good in terms of input lag though, there are more factors than just polling rate that influence how well a keyboard performs (debouncing, scan rate, general firmware quality, etc.).
> 
> > KeyboardDataQueueSize
> 
> Changing this can cause dropped inputs with basically 0 input lag improvement. I wouldn't recommend it.
> 
> > disable high precision event timer in the device manager
> 
> This does nothing, you have to disable it through a different method. I won't say what that method is though, because it hurts performance on newer windows versions (it can only improve performance on very outdated versions of Windows 10).
> 
> > i feel in stuck rn as there is not much i can do to make my lenovo ideapad keyboard to feel so instant.
> 
> Buy a SayoDevice O3C from AliExpress.

wait what about the firmware adjust part? As you heard eariler in the post "i heard that you can adjust the firmware of the ps/2 keyboard but idk where is it?"

**Comment by theyareonit** [comment]
> wait what about the firmware adjust part

It's possible that some keyboards have software that lets you change certain aspects about it that affect performance. Unlikely on a laptop keyboard though.

**Comment by theyareonit** [comment]
> how much cps (15, 20 or 30 cps?) before i notices the lag

Probably like 100cps, which is probably faster than your keyboard lets you spam anyway.

**Comment by JerichoGesolgani** [comment]
> > how much cps (15, 20 or 30 cps?) before i notices the lag
> 
> Probably like 100cps, which is probably faster than your keyboard lets you spam anyway.

That excellent sign it not like extreme demon like 100cps that like physically impossible for a human to spam that fast anyways tho but i notice something while i doing some researchs i heard that setting KeyBoardData thing in registry is suggested to set at 30 or 40 in decimal as it considered to be middle ground not make a device usable, do you agree with this or not also i kinda forgot the default vaule so idk

**Comment by JerichoGesolgani** [comment]
> > how much cps (15, 20 or 30 cps?) before i notices the lag
> 
> Probably like 100cps, which is probably faster than your keyboard lets you spam anyway.

That excellent sign it not like extreme demon require 100cps that like physically impossible for a human to spam that fast anyways tho but i notice something while i doing some researchs i heard that setting KeyBoardData thing in registry is suggested to set at 30 or 40 in decimal as it considered to be middle ground not make a device usable, do you agree with this or not also i kinda forgot the default vaule so idk
