### ISSUE TITLE
Visual trail bug

### ISSUE THREAD

**Issue by Mismar0305** [theyareonit/Click-Between-Frames#8]
there is a small visual bug with the trail, i've only noticed it with the wave and i'm not sure if it's present on the other gamemodes

![image_2024-04-10_163646756](https://github.com/theyareonit/Click-Between-Frames/assets/166631163/86016a0b-71f7-4fcf-b262-4e297a297376)
the trail (not the wave trail) is cutting corners

![image_2024-04-10_164331540](https://github.com/theyareonit/Click-Between-Frames/assets/166631163/97ab511e-0d32-4ac6-ab07-1291c9637389)
the mini wave trail behaving strangely

i have tested and the bug is not present without the mod enabled

**Comment by theyareonit** [comment]
I believe the mod might still have some bugs with Wave Trail Drag Fix if you're using that? I removed the incompatibility from the mod.json, but I'm pretty sure it still doesn't work perfectly.

**Comment by theyareonit** [comment]
fixed in https://github.com/theyareonit/Click-Between-Frames/commit/7925c06f17219691f16f6560c7aa5fe308881717 i think
