### ISSUE TITLE
Weird Input Problem Specific to Mice on an Arch-based Linux Distro

### ISSUE THREAD

**Issue by u2chr2** [theyareonit/Click-Between-Frames#83]
I am on an arch-based Linux distro (EndeavourOS to be more specific) and my mouse (a Glorious Model I), randomly stops working while using CBF. My keyboard continues to work as intended, however, my mouse randomly stops registering inputs in-game after a few minutes of playing (however menus still work) until I restart Geometry Dash. Making any inputs as the level is loading from the main menu counts towards the CPS counter in Mega Hack v8 and I can buffer inputs that way (I'm guessing that is because CBF isn't enabled in those scenarios). This problem does not occur on Windows 11 23H2.

I am on Wayland, KDE Plasma (6.2.3), on an Intel Arc A750 and Intel i3 12100F using the custom 6.12.0-rc7-273-tkg-eevdf kernel and I am running the game with Proton GE 9-20 using Bottles.

**Comment by theyareonit** [comment]
Your mouse is probably disconnecting and reconnecting periodically (the mod currently doesn't support replugging input devices on Linux). Try different USB ports maybe.

**Comment by u2chr2** [comment]
Oh yeah, my mouse's cable is pretty messed up and disconnects for a few seconds when I move it sometimes. I didn't notice since my USB disconnect and connect sounds are muted in Linux and I thought it was just happening in random. Seems like that was the cause, thanks!
